manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: germain-gadel
      revision: test1
      import: app/west.yml
  self:
    path: config
