manifest:
  remotes:
    - name: germain-gadel
      url-base: https://github.com/germain-gadel
  projects:
    - name: zmk
      remote: germain-gadel
      import: app/west.yml
  self:
    path: config
