manifest:
  remotes:
    - name: germain-gadel
      url-base: https://github.com/germain-gadel
  projects:
    - name: zmk
      remote: germain-gadel
      revision: rev1
      import: config/west.yml
  self:
    path: config
